import Head from 'next/head'
import { TabGroup } from '@statikly/funk'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { format } from "date-fns";


export default function Home({ data, reviewsdata }) {


	return (
		<div >
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="px-5 py-24 dark:bg-gray-800 dark:text-gray-100">
				<div className="container grid grid-cols-12 mx-auto gap-y-6 md:gap-10">
					<div className="flex flex-col justify-between col-span-12 py-2 space-y-8 md:space-y-16 md:col-span-3">
						<div className="flex flex-col space-y-8 md:space-y-12">
							<div className="flex flex-col space-y-2">
								<h3 className="flex items-center space-x-2 dark:text-gray-400">
									<span className="flex-shrink-0 w-2 h-2 uppercase rounded-full dark:bg-pink-400"></span>
									<span className="text-xs font-bold tracking-wider uppercase">Exclusive</span>
								</h3>
								<Link href={'/'}><a rel="noopener noreferrer" href="#" className="font-serif hover:underline">Donec sed elit quis odio mollis dignissim eget et nulla.</a></Link>
								<p className="text-xs dark:text-gray-400">47 minutes ago by
									<Link href={'/'}><a rel="noopener noreferrer" href="#" className="hover:underline dark:text-pink-400">Leroy Jenkins</a></Link>
								</p>
							</div>
							<div className="flex flex-col space-y-2">
								<h3 className="flex items-center space-x-2 dark:text-gray-400">
									<span className="flex-shrink-0 w-2 h-2 uppercase rounded-full dark:bg-pink-400"></span>
									<span className="text-xs font-bold tracking-wider uppercase">Exclusive</span>
								</h3>
								<Link href={'/'}><a rel="noopener noreferrer" href="#" className="font-serif hover:underline">Ut fermentum nunc quis ipsum laoreet condimentum.</a></Link>
								<p className="text-xs dark:text-gray-400">2 hours ago by
									<Link href={'/'}><a rel="noopener noreferrer" href="#" className="hover:underline dark:text-pink-400">Leroy Jenkins</a></Link>
								</p>
							</div>
							<div className="flex flex-col space-y-2">
								<h3 className="flex items-center space-x-2 dark:text-gray-400">
									<span className="flex-shrink-0 w-2 h-2 uppercase rounded-full dark:bg-pink-400"></span>
									<span className="text-xs font-bold tracking-wider uppercase">Exclusive</span>
								</h3>
								<Link href={'/'}><a rel="noopener noreferrer" href="#" className="font-serif hover:underline">Nunc nec ipsum lobortis, pulvinar neque sed.</a></Link>
								<p className="text-xs dark:text-gray-400">4 hours ago by
									<Link href={'/'}><a rel="noopener noreferrer" href="#" className="hover:underline dark:text-pink-400">Leroy Jenkins</a></Link>
								</p>
							</div>
						</div>
						<div className="flex flex-col w-full space-y-2">
							<div className="flex w-full h-1 bg-opacity-10 dark:bg-pink-400">
								<div className="w-1/2 h-full dark:bg-pink-400"></div>
							</div>
							<Link href={'/'}><a rel="noopener noreferrer" href="#" className="flex items-center justify-between w-full">
								<span className="text-xs font-bold tracking-wider uppercase">See more exclusives</span>
								<svg viewBox="0 0 24 24" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" className="w-4 strokeCurrent dark:text-pink-400">
									<line x1="5" y1="12" x2="19" y2="12"></line>
									<polyline points="12 5 19 12 12 19"></polyline>
								</svg>
							</a></Link>
						</div>
					</div>
					{data.slice(0, 1).map((post, index) => {

						
						return (<Link key={index} href={`/blog/${post['slug']}`}>
							<div className='relative flex col-span-12 bg-center bg-no-repeat bg-cover  xl:col-span-6 lg:col-span-5 md:col-span-9 min-h-96' style={{ background: `url(${post['_embedded']['wp:featuredmedia'][0]['source_url']})`, backgroundRepeat: 'no-repeat', backgroundSize: 'cover' }}>
								<span className="absolute px-1 pb-2 text-xs font-bold uppercase border-b-2 left-6 top-6 dark:border-pink-400 dark:text-gray-100">paris, france</span>
								<Link href={'/'}><a className="flex flex-col items-center justify-end p-6 text-center sm:p-8 group dark:via-transparent flex-grow-1 bg-gradient-to-b dark:from-gray-900 dark:to-gray-900">
									<span className="flex items-center mb-4 space-x-2 dark:text-pink-400">
										<span className="relative flex-shrink-0 w-2 h-2 rounded-full dark:bg-pink-400">
											<span className="absolute flex-shrink-0 w-3 h-3 rounded-full -left-1 -top-1 animate-ping dark:bg-pink-400"></span>
										</span>
										<span className="text-sm font-bold">Live</span>
									</span>
									<h1 rel="noopener noreferrer" href="#" className="font-serif text-2xl font-semibold group-hover:underline dark:text-gray-100">{post['title']['rendered']}</h1>
								</a></Link>
							</div>
						</Link>)
					})}
					<div className="hidden py-2 xl:col-span-3 lg:col-span-4 md:hidden lg:block">
					<TabGroup numTabs={3} direction={TabGroup.direction.HORIZONTAL}>
						<div className="mb-8 space-x-5 border-b-2 border-opacity-10 dark:border-pink-400">
							
								<TabGroup.TabList className='space-x-4'>
								<TabGroup.Tab index={0} className="pb-5 text-xs font-bold uppercase border-b-2  duration-150"
								activeClassName="text-white dark:border-pink-400"
								inactiveClassName="text-gray-500 border-transparent"
								>Top News</TabGroup.Tab>
								<TabGroup.Tab
            					index={1} className="pb-5 text-xs font-bold uppercase border-b-2  "
								activeClassName="text-white dark:border-pink-400"
            					inactiveClassName="text-gray-500 border-transparent"
								>Reviews</TabGroup.Tab>
								
								</TabGroup.TabList>
						</div>
						<TabGroup.TabPanel
          				index={0}
          				className="transition-all transform h-64"
          				activeClassName="opacity-100 duration-500 translate-x-0"
          				inactiveClassName="absolute opacity-0 -translate-x-2">
						<div className="flex flex-col divide-y divide-gray-700">
							{data.slice(1, 5).map((post, index) => {
								console.log(post)
								var olddate = new Date(post['date']);
								var today = format(olddate, "MMMM do, yyyy H:mma");
								return <Link key={index} href={`/blog/${post['slug']}`}>
									<div className="flex px-1 py-4">
										<img alt="" className="flex-shrink-0 object-cover w-20 h-20 mr-4 dark:bg-gray-500" src={post['_embedded']['wp:featuredmedia'][0]['source_url']} />
										<div className="flex flex-col flex-grow">
											<Link href={'/'}><a rel="noopener noreferrer" href="#" className="font-serif hover:underline font-normal text-[15px]" dangerouslySetInnerHTML={{__html: post['title']['rendered'] }} ></a></Link>
											<p className="mt-auto text-xs dark:text-gray-400">
												<Link href={'/'}><a rel="noopener noreferrer" href="#" className="block dark:text-blue-400 lg:ml-2 lg:inline hover:underline">Politics</a></Link>
											</p>
										</div>
									</div>
								</Link>
							})}
						</div>
						</TabGroup.TabPanel>
						<TabGroup.TabPanel
          				index={1}
          				className="transition-all transform h-64"
          				activeClassName="opacity-100 duration-500 translate-x-0"
          				inactiveClassName="absolute opacity-0 -translate-x-2">
						<div className="flex flex-col divide-y divide-gray-700">
							{reviewsdata.slice(0, 4).map((post, index) => {
								console.log(post)
								var olddate = new Date(post['date']);
								var today = format(olddate, "MMMM do, yyyy H:mma");
								return <Link key={index} href={`/blog/${post['slug']}`}>
									<div className="flex px-1 py-4">
										<img alt="" className="flex-shrink-0 object-cover w-20 h-20 mr-4 dark:bg-gray-500" src={post['_embedded']['wp:featuredmedia'][0]['source_url']} />
										<div className="flex flex-col flex-grow">
											<Link href={'/'}><a rel="noopener noreferrer" href="#" className="font-serif hover:underline font-normal text-[15px]" dangerouslySetInnerHTML={{__html: post['title']['rendered'].slice(0,60) }}></a></Link>
											<p className="mt-auto text-xs dark:text-gray-400">5 minutes ago
												<Link href={'/'}><a rel="noopener noreferrer" href="#" className="block dark:text-blue-400 lg:ml-2 lg:inline hover:underline">Politics</a></Link>
											</p>
										</div>
									</div>
								</Link>
							})}
						</div>
						</TabGroup.TabPanel>
						</TabGroup>
					</div>
				</div>
			</section>
				
		</div>
	)
}

export async function getServerSideProps() {
	const topnews = await fetch('http://headless.local/wp-json/wp/v2/posts?&categories=3&order=asc&_embed');
	const data = await topnews.json();
	const reviews = await fetch('http://headless.local/wp-json/wp/v2/posts?&categories=5&_embed');
	const reviewsdata = await reviews.json();
	return { props: { data , reviewsdata } }
}